project:
  type: website

website:
  title: "Hidde van de Beek"
  navbar:
    left:
      - about.qmd
      - href: CV.pdf
        text: CV
      - Projects.qmd  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



