project:
  type: website

website:
  title: "Hidde van de Beek"
  navbar:
    left:
      - href: about.qmd
        text: ABOUT ME
      - href: CV.pdf
        text: CV
      - href: Projects.qmd  
        text: PROJECTS
      - href: admr/index.qmd
        text: ADMR

format:
  html:
    theme: 
      light: cosmo
      dark: solar
    css: styles.css
    toc: true



